package meusalao;

import Controller.MenuPrincipalController;

public class InicialCliente extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form InicialCliente
     */
    public InicialCliente() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImTelaCliente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lblAgendamento = new javax.swing.JMenu();
        ItMenuAgendamento = new javax.swing.JMenuItem();
        ItMarcadoAgrendamento = new javax.swing.JMenuItem();
        lblProcedimentos = new javax.swing.JMenu();
        ItMenuProcedimentos = new javax.swing.JMenuItem();
        lblPerfil = new javax.swing.JMenu();
        ItMenuMeuPerfil = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        ItSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImTelaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/logo.jpg"))); // NOI18N
        getContentPane().add(ImTelaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/calendar_icon_129357.png"))); // NOI18N
        lblAgendamento.setText("Agendamento");

        ItMenuAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/1486564407-plus-green_81521.png"))); // NOI18N
        ItMenuAgendamento.setText("Novo");
        ItMenuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItMenuAgendamentoActionPerformed(evt);
            }
        });
        lblAgendamento.add(ItMenuAgendamento);

        ItMarcadoAgrendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/4552611-check-listing-loupe-magnifier-magnifying-glass-search_121392.png"))); // NOI18N
        ItMarcadoAgrendamento.setText("Marcado");
        ItMarcadoAgrendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItMarcadoAgrendamentoActionPerformed(evt);
            }
        });
        lblAgendamento.add(ItMarcadoAgrendamento);

        jMenuBar1.add(lblAgendamento);

        lblProcedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/Badadd_icon-icons.com_51213.png"))); // NOI18N
        lblProcedimentos.setText("Procedimentos");

        ItMenuProcedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/free-30-instagram-stories-icons11_122558.png"))); // NOI18N
        ItMenuProcedimentos.setText("Procedimentos");
        ItMenuProcedimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItMenuProcedimentosActionPerformed(evt);
            }
        });
        lblProcedimentos.add(ItMenuProcedimentos);

        jMenuBar1.add(lblProcedimentos);

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/idcard_119573.png"))); // NOI18N
        lblPerfil.setText("Perfil");

        ItMenuMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/status_doc_positive_accepted_checked_user_profile_icon_220280.png"))); // NOI18N
        ItMenuMeuPerfil.setText("Meu Perfil");
        ItMenuMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItMenuMeuPerfilActionPerformed(evt);
            }
        });
        lblPerfil.add(ItMenuMeuPerfil);

        jMenuBar1.add(lblPerfil);

        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/communication_information_aid_disclaimer_customer_service_about_guide_help_info_icon_210836.png"))); // NOI18N
        MenuSobre.setText("Sobre");

        ItSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/about-48_44860.png"))); // NOI18N
        ItSobre.setText("Sobre");
        ItSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItSobreActionPerformed(evt);
            }
        });
        MenuSobre.add(ItSobre);

        jMenuBar1.add(MenuSobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItMenuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItMenuAgendamentoActionPerformed
        this.controller.navegarParaAgenda();
    }//GEN-LAST:event_ItMenuAgendamentoActionPerformed

    private void ItMarcadoAgrendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItMarcadoAgrendamentoActionPerformed
        this.controller.navegarParaAgendamento();
    }//GEN-LAST:event_ItMarcadoAgrendamentoActionPerformed

    private void ItMenuProcedimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItMenuProcedimentosActionPerformed
        this.controller.navegarParaProcedimentos();
    }//GEN-LAST:event_ItMenuProcedimentosActionPerformed

    private void ItMenuMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItMenuMeuPerfilActionPerformed
        this.controller.navegarParaMeuPerfil();
    }//GEN-LAST:event_ItMenuMeuPerfilActionPerformed

    private void ItSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItSobreActionPerformed
        this.controller.navegarParaSobreNos();
    }//GEN-LAST:event_ItSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImTelaCliente;
    private javax.swing.JMenuItem ItMarcadoAgrendamento;
    private javax.swing.JMenuItem ItMenuAgendamento;
    private javax.swing.JMenuItem ItMenuMeuPerfil;
    private javax.swing.JMenuItem ItMenuProcedimentos;
    private javax.swing.JMenuItem ItSobre;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lblAgendamento;
    private javax.swing.JMenu lblPerfil;
    private javax.swing.JMenu lblProcedimentos;
    // End of variables declaration//GEN-END:variables

    public static class meusalao {

        public meusalao() {
        }
    }
}
