package meusalao;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class NovoAgendamento extends javax.swing.JFrame {

   private final AgendaController controller;
   
    public NovoAgendamento() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblAgenda = new javax.swing.JLabel();
        IMFundoAgenda = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        JComboBoxCliente = new javax.swing.JComboBox<>();
        lblServico = new javax.swing.JLabel();
        JComboBoxServico = new javax.swing.JComboBox<>();
        lblValor = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        lblObservacao = new javax.swing.JLabel();
        bxtxtObservacao = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        lblData = new javax.swing.JLabel();
        bxData = new javax.swing.JFormattedTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        bttAgendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        lblImagemPrincipal = new javax.swing.JLabel();
        IMFundoNovoAgendamento = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAgenda.setForeground(new java.awt.Color(255, 255, 255));
        lblAgenda.setText("Agenda");
        getContentPane().add(lblAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        IMFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 40));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        TextID.setText("0");
        getContentPane().add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Cliente");
        lblNome.setToolTipText("");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        getContentPane().add(JComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, -1));

        lblServico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblServico.setForeground(new java.awt.Color(255, 255, 255));
        lblServico.setText("Serviço");
        getContentPane().add(lblServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        JComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxServicoItemStateChanged(evt);
            }
        });
        JComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, -1));

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor R$");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        TextValor.setText("0");
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 140, -1));

        lblObservacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblObservacao.setForeground(new java.awt.Color(255, 255, 255));
        lblObservacao.setText("Observação");
        getContentPane().add(lblObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        TextObservacao.setColumns(20);
        TextObservacao.setRows(5);
        bxtxtObservacao.setViewportView(TextObservacao);

        getContentPane().add(bxtxtObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 180, 120));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        bxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        bxData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxDataActionPerformed(evt);
            }
        });
        getContentPane().add(bxData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, -1));

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("Hora");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, -1));

        bttAgendar.setBackground(new java.awt.Color(153, 0, 0));
        bttAgendar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttAgendar.setForeground(new java.awt.Color(255, 255, 255));
        bttAgendar.setText("Agendar");
        bttAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(bttAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 180, -1));

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor R$", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 570, 120));

        lblImagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telalogin.jpg"))); // NOI18N
        getContentPane().add(lblImagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        IMFundoNovoAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoNovoAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxServicoItemStateChanged
       this.controller.atualizaValor();
    }//GEN-LAST:event_JComboBoxServicoItemStateChanged

    private void JComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxServicoActionPerformed

    private void bttAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgendarActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_bttAgendarActionPerformed

    private void bxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxDataActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMFundoAgenda;
    private javax.swing.JLabel IMFundoNovoAgendamento;
    private javax.swing.JComboBox<String> JComboBoxCliente;
    private javax.swing.JComboBox<String> JComboBoxServico;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JButton bttAgendar;
    private javax.swing.JFormattedTextField bxData;
    private javax.swing.JScrollPane bxtxtObservacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImagemPrincipal;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
    }
    

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }

    public JComboBox<String> getJComboBoxCliente() {
        return JComboBoxCliente;
    }

    public void setJComboBoxCliente(JComboBox<String> JComboBoxCliente) {
        this.JComboBoxCliente = JComboBoxCliente;
    }

    public JComboBox<String> getJComboBoxServico() {
        return JComboBoxServico;
    }

    public void setJComboBoxServico(JComboBox<String> JComboBoxServico) {
        this.JComboBoxServico = JComboBoxServico;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTextID() {
        return TextID;
    }

    public void setTextID(JTextField TextID) {
        this.TextID = TextID;
    }

    public JFormattedTextField getBxData() {
        return bxData;
    }

    public void setBxData(JFormattedTextField bxData) {
        this.bxData = bxData;
    }

    public JTextField getTxtHora() {
        return txtHora;
    }

    public void setTxtHora(JTextField txtHora) {
        this.txtHora = txtHora;
    }


    public JTextArea getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao) {
        this.TextObservacao = TextObservacao;
    }

    
   
}
