package meusalao;

public class NovoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NovoCliente
     */
    public NovoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTituloNovoCliente = new javax.swing.JLabel();
        IMFundoNovoCliente = new javax.swing.JLabel();
        lblIMFundoLogin = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblEmailCliente = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lblSenhaCliente = new javax.swing.JLabel();
        txtSenhaCliente = new javax.swing.JPasswordField();
        lblTelefoneCliente = new javax.swing.JLabel();
        txtTelefoneCliente = new javax.swing.JFormattedTextField();
        lblSexoCliente = new javax.swing.JLabel();
        lblSexoMasc = new javax.swing.JRadioButton();
        lblSexoFem = new javax.swing.JRadioButton();
        lblRG = new javax.swing.JLabel();
        txtRGCliente = new javax.swing.JTextField();
        lblEnderecoCliente = new javax.swing.JLabel();
        txtEnderecoCliente = new javax.swing.JTextField();
        lblCEPCliente = new javax.swing.JLabel();
        txtCEPCliente = new javax.swing.JTextField();
        bttCadastrarCliente = new javax.swing.JButton();
        IMTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/character_fantasy_gorgon_medusa_monster_icon_193265.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, -1));

        lblTituloNovoCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloNovoCliente.setText("Novo Cadastro");
        getContentPane().add(lblTituloNovoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        IMFundoNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoNovoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 260, 40));

        lblIMFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(lblIMFundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 650, 90));

        lblNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCliente.setText("Nome:");
        getContentPane().add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeCliente.setToolTipText("");
        getContentPane().add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 230, 30));

        lblEmailCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmailCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailCliente.setText("E-mail:");
        getContentPane().add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        txtEmailCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, 30));

        lblSenhaCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSenhaCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaCliente.setText("Senha:");
        getContentPane().add(lblSenhaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        txtSenhaCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenhaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 230, 30));

        lblTelefoneCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTelefoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefoneCliente.setText("Telefone:");
        getContentPane().add(lblTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        txtTelefoneCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, 30));

        lblSexoCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSexoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblSexoCliente.setText("Sexo:");
        getContentPane().add(lblSexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lblSexoMasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSexoMasc.setForeground(new java.awt.Color(255, 255, 255));
        lblSexoMasc.setText("Masculino");
        getContentPane().add(lblSexoMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 30));

        lblSexoFem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSexoFem.setForeground(new java.awt.Color(255, 255, 255));
        lblSexoFem.setText("Feminino");
        getContentPane().add(lblSexoFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 120, 30));

        lblRG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRG.setForeground(new java.awt.Color(255, 255, 255));
        lblRG.setText("RG:");
        getContentPane().add(lblRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        txtRGCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtRGCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 90, 30));

        lblEnderecoCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnderecoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblEnderecoCliente.setText("Endereço:");
        getContentPane().add(lblEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtEnderecoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 230, 30));

        lblCEPCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCEPCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCEPCliente.setText("CEP:");
        getContentPane().add(lblCEPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        txtCEPCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtCEPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 90, 30));

        bttCadastrarCliente.setBackground(new java.awt.Color(153, 0, 0));
        bttCadastrarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bttCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bttCadastrarCliente.setText("Cadastrar");
        getContentPane().add(bttCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 230, -1));

        IMTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telalogin.jpg"))); // NOI18N
        getContentPane().add(IMTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaClienteActionPerformed

    private void txtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMFundoNovoCliente;
    private javax.swing.JLabel IMTelaLogin;
    private javax.swing.JButton bttCadastrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCEPCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblIMFundoLogin;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSenhaCliente;
    private javax.swing.JLabel lblSexoCliente;
    private javax.swing.JRadioButton lblSexoFem;
    private javax.swing.JRadioButton lblSexoMasc;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblTituloNovoCliente;
    private javax.swing.JTextField txtCEPCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtRGCliente;
    private javax.swing.JPasswordField txtSenhaCliente;
    private javax.swing.JFormattedTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
