package meusalao;

public class Procedimentos extends javax.swing.JFrame {

    /**
     * Creates new form Procedimentos
     */
    public Procedimentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloProcedimentos = new javax.swing.JLabel();
        tbProcedimentos = new javax.swing.JScrollPane();
        TbProcedimentos = new javax.swing.JTable();
        IMProcedimentos = new javax.swing.JLabel();
        IMFundoProcedimentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloProcedimentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloProcedimentos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloProcedimentos.setText("Procedimentos");
        getContentPane().add(lblTituloProcedimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        tbProcedimentos.setForeground(new java.awt.Color(255, 255, 255));

        TbProcedimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Corte Simples", "R$ 18,00"},
                {"2", "Corte Degradê", "R$ 25,00"},
                {"3", "Barba Simples", "R$ 15,00"},
                {"4", "Barba Desenhada", "R$ 22,00"},
                {"5", "Sombrancelhas", "R$ 60,00"},
                {"6", "Penteados Feminino", "R$ 70,00"},
                {"7", "Aplicação de Ampola", "R$ 20,00"},
                {"8", "Botox Capilar", "R$ 120,00"},
                {"9", "Cauterização a Frio", "R$ 180,00"},
                {"10", "Celophane", "R$ 120,00"},
                {"11", "Coloração", "R$ 100,00"},
                {"12", "Corte com Gil Madureira", "R$ 160,00"},
                {"13", "Corte Feminino", "R$ 150,00"},
                {"14", "Escova", "R$ 70,00"},
                {"15", "Escova Catiônica", "R$ 120,00"},
                {"16", "Escova Definitiva", "R$ 400,00"},
                {"17", "Escova Inteligente", "R$ 180,00"},
                {"18", "Escova Reconstrutiva", "R$ 160,00"},
                {"19", "Escova Reestruturante", "R$ 160,00"},
                {"20", "Henna", "R$ 25,00"},
                {"21", "Design Sobrancelha", "R$ 50,00"},
                {"22", "Sombrancelha", "R$ 60,00"},
                {"23", "Micropigmentação Fio a Fio", "R$ 170,00"},
                {"24", "Micropigmentação Labial", "R$ 100,00"},
                {"25", "Neutralização Labial", "R$ 90,00"},
                {"26", "Hidratação", "R$ 100,00"},
                {"27", "Hidratação de Queratina", "R$ 140,00"},
                {"28", "Initialiste Kérastase", "R$ 220,00"},
                {"29", "Shampoo (Lavagem)", "R$ 20,00"},
                {"30", "Mechas", "R$ 150,00"},
                {"31", "Limpeza de Pele", "R$ 70,00"},
                {"32", "Tintura Inoa", "R$ 130,00"},
                {"33", "Penteado Noiva", "R$ 200,00"},
                {"34", "Penetrait", "R$ 260,00"}
            },
            new String [] {
                "Código", "Procedimentos", "Valores"
            }
        ));
        tbProcedimentos.setViewportView(TbProcedimentos);

        getContentPane().add(tbProcedimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 520, 340));

        IMProcedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMProcedimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 650, 410));

        IMFundoProcedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telalogin.jpg"))); // NOI18N
        getContentPane().add(IMFundoProcedimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procedimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procedimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procedimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procedimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procedimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMFundoProcedimentos;
    private javax.swing.JLabel IMProcedimentos;
    private javax.swing.JTable TbProcedimentos;
    private javax.swing.JLabel lblTituloProcedimentos;
    private javax.swing.JScrollPane tbProcedimentos;
    // End of variables declaration//GEN-END:variables
}
