package meusalao;

public class SobreNos extends javax.swing.JFrame {

    /**
     * Creates new form SobreNos
     */
    public SobreNos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloSobreNos = new javax.swing.JLabel();
        lblTextoSobreNos = new javax.swing.JLabel();
        lblTextoSobreNos2 = new javax.swing.JLabel();
        IMInstagram = new javax.swing.JLabel();
        IMInstagram1 = new javax.swing.JLabel();
        IMTelefone = new javax.swing.JLabel();
        IMTelefone1 = new javax.swing.JLabel();
        IMFundoSobreNos3 = new javax.swing.JLabel();
        IMFundoSobreNos2 = new javax.swing.JLabel();
        lblTextoSobreNos1 = new javax.swing.JLabel();
        IMFundoSobreNos = new javax.swing.JLabel();
        IMFundoSobreNos1 = new javax.swing.JLabel();
        lblEncontreNos = new javax.swing.JLabel();
        lblSobreNos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSobreNos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloSobreNos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSobreNos.setText("SOBRE NÓS");
        getContentPane().add(lblTituloSobreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        lblTextoSobreNos.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        lblTextoSobreNos.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoSobreNos.setText("Programa desenvolvido em Java pelos alunos do curso de Telemática Jefferson "); // NOI18N
        getContentPane().add(lblTextoSobreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 620, -1));

        lblTextoSobreNos2.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        lblTextoSobreNos2.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoSobreNos2.setText("Adriel Moreira de Araújo e Ana Vitória de Sousa Lima, afins de conclusão");
        getContentPane().add(lblTextoSobreNos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 490, -1));

        IMInstagram.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        IMInstagram.setForeground(new java.awt.Color(255, 255, 255));
        IMInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/1497553304-104_84834.png"))); // NOI18N
        IMInstagram.setText("@i_banid0");
        IMInstagram.setToolTipText("");
        getContentPane().add(IMInstagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 140, -1));

        IMInstagram1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        IMInstagram1.setForeground(new java.awt.Color(255, 255, 255));
        IMInstagram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/1497553304-104_84834.png"))); // NOI18N
        IMInstagram1.setText("@raridade_cdo");
        getContentPane().add(IMInstagram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, -1));

        IMTelefone.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        IMTelefone.setForeground(new java.awt.Color(255, 255, 255));
        IMTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/Phone_31105.png"))); // NOI18N
        IMTelefone.setText("(88) 9.9967-8262");
        getContentPane().add(IMTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, -1));

        IMTelefone1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IMTelefone1.setForeground(new java.awt.Color(255, 255, 255));
        IMTelefone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/Phone_31105.png"))); // NOI18N
        IMTelefone1.setText("(88) 9.9873-6517");
        getContentPane().add(IMTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        IMFundoSobreNos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoSobreNos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 220, 70));

        IMFundoSobreNos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoSobreNos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 200, 70));

        lblTextoSobreNos1.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        lblTextoSobreNos1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoSobreNos1.setText("na disciplina de POO orientada pelo Profº Samuel Soares.");
        getContentPane().add(lblTextoSobreNos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        IMFundoSobreNos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoSobreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 580, 190));

        IMFundoSobreNos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMFundoSobreNos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 280, 40));

        lblEncontreNos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEncontreNos.setForeground(new java.awt.Color(255, 255, 255));
        lblEncontreNos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/account_profile_user_avatar_man_people_team_group_users_icon_210760.png"))); // NOI18N
        lblEncontreNos.setText("Encontre nós:");
        getContentPane().add(lblEncontreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        lblSobreNos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telalogin.jpg"))); // NOI18N
        getContentPane().add(lblSobreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SobreNos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SobreNos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SobreNos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SobreNos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SobreNos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMFundoSobreNos;
    private javax.swing.JLabel IMFundoSobreNos1;
    private javax.swing.JLabel IMFundoSobreNos2;
    private javax.swing.JLabel IMFundoSobreNos3;
    private javax.swing.JLabel IMInstagram;
    private javax.swing.JLabel IMInstagram1;
    private javax.swing.JLabel IMTelefone;
    private javax.swing.JLabel IMTelefone1;
    private javax.swing.JLabel lblEncontreNos;
    private javax.swing.JLabel lblSobreNos;
    private javax.swing.JLabel lblTextoSobreNos;
    private javax.swing.JLabel lblTextoSobreNos1;
    private javax.swing.JLabel lblTextoSobreNos2;
    private javax.swing.JLabel lblTituloSobreNos;
    // End of variables declaration//GEN-END:variables
}
