package meusalao;

import Controller.LoginController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class TelaInicialGerente extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form TelaInicialGerente
     */
    public TelaInicialGerente() {
        initComponents();
        controller = new LoginController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblIMLogin = new javax.swing.JLabel();
        lblIMFundoLogin = new javax.swing.JLabel();
        lblChamaUsuario = new javax.swing.JLabel();
        lblNovoUsuario = new javax.swing.JLabel();
        lblreCAPTCHA = new javax.swing.JLabel();
        lblreCAPTCHA1 = new javax.swing.JLabel();
        lblreCAPTCHASabiaMais = new javax.swing.JLabel();
        IMLogin = new javax.swing.JLabel();
        ckLembre = new java.awt.Checkbox();
        lblAjuda = new javax.swing.JLabel();
        lblPrincipal = new javax.swing.JLabel();
        lblLoginGerente = new javax.swing.JLabel();
        txtLoginGerente = new javax.swing.JTextField();
        lblSenhaGerente = new javax.swing.JLabel();
        txtSenhaGerente = new javax.swing.JPasswordField();
        BtGerente = new javax.swing.JButton();
        lblTelaLoginGerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Seja bem-vindo(a) ao Medusa Hair Salon");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        lblIMLogin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblIMLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblIMLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/character_fantasy_gorgon_medusa_monster_icon_193265.png"))); // NOI18N
        lblIMLogin.setToolTipText("");
        getContentPane().add(lblIMLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblIMFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(lblIMFundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 20, 670, 90));

        lblChamaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblChamaUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChamaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblChamaUsuario.setText("Novo por aqui?");
        getContentPane().add(lblChamaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 20));

        lblNovoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblNovoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNovoUsuario.setText("Cadastre-se agora");
        lblNovoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(lblNovoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 20));

        lblreCAPTCHA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblreCAPTCHA.setForeground(new java.awt.Color(255, 255, 255));
        lblreCAPTCHA.setText("Essta página é protegida pelo reCAPTCHA para");
        getContentPane().add(lblreCAPTCHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        lblreCAPTCHA1.setBackground(new java.awt.Color(255, 255, 255));
        lblreCAPTCHA1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblreCAPTCHA1.setForeground(new java.awt.Color(255, 255, 255));
        lblreCAPTCHA1.setText("garantir que você não é um robô.");
        getContentPane().add(lblreCAPTCHA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        lblreCAPTCHASabiaMais.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblreCAPTCHASabiaMais.setForeground(new java.awt.Color(51, 102, 255));
        lblreCAPTCHASabiaMais.setText("Saiba mais.");
        getContentPane().add(lblreCAPTCHASabiaMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 20));

        IMLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(IMLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 300, 70));

        ckLembre.setBackground(new java.awt.Color(255, 255, 255));
        ckLembre.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ckLembre.setLabel("Lembre-se de mim");
        getContentPane().add(ckLembre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 130, -1));

        lblAjuda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAjuda.setForeground(new java.awt.Color(255, 255, 255));
        lblAjuda.setText("Precisa de ajuda?");
        getContentPane().add(lblAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        lblPrincipal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipal.setText("Entrar");
        getContentPane().add(lblPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        lblLoginGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoginGerente.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginGerente.setText("Login:");
        getContentPane().add(lblLoginGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtLoginGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtLoginGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 250, -1));

        lblSenhaGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSenhaGerente.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaGerente.setText("Senha:");
        getContentPane().add(lblSenhaGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        txtSenhaGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtSenhaGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, -1));

        BtGerente.setBackground(new java.awt.Color(153, 0, 0));
        BtGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtGerente.setForeground(new java.awt.Color(255, 255, 255));
        BtGerente.setActionCommand("Entrar");
        BtGerente.setLabel("Acessar");
        BtGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(BtGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 250, 30));

        lblTelaLoginGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telalogin.jpg"))); // NOI18N
        getContentPane().add(lblTelaLoginGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGerenteActionPerformed
        // Executa quando clico no botão
        this.controller.entrarNoSistema();
        System.out.println(txtLoginGerente.getText());
        System.out.println(txtSenhaGerente.getText());
        
    }//GEN-LAST:event_BtGerenteActionPerformed

    private void lblNovoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoUsuarioMouseClicked
        NovoCliente novoCliente = new NovoCliente();
        novoCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblNovoUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGerente;
    private javax.swing.JLabel IMLogin;
    private java.awt.Checkbox ckLembre;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblChamaUsuario;
    private javax.swing.JLabel lblIMFundoLogin;
    private javax.swing.JLabel lblIMLogin;
    private javax.swing.JLabel lblLoginGerente;
    private javax.swing.JLabel lblNovoUsuario;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblSenhaGerente;
    private javax.swing.JLabel lblTelaLoginGerente;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblreCAPTCHA;
    private javax.swing.JLabel lblreCAPTCHA1;
    private javax.swing.JLabel lblreCAPTCHASabiaMais;
    private javax.swing.JTextField txtLoginGerente;
    private javax.swing.JPasswordField txtSenhaGerente;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
        // View recebe uma mensagem que ela não sabe qual é exibe ela na tela
    }

    public JTextField getTxtLoginGerente() {
        return txtLoginGerente;
    }

    public void setTxtLoginGerente(JTextField txtLoginGerente) {
        this.txtLoginGerente = txtLoginGerente;
    }

    public JPasswordField getTxtSenhaGerente() {
        return txtSenhaGerente;
    }

    public void setTxtSenhaGerente(JPasswordField txtSenhaGerente) {
        this.txtSenhaGerente = txtSenhaGerente;
    }

    public Object getTextUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void exibirMensagem(String usuario_ou_senha_invalidos) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
